### ISSUE TITLE
WARNING: org.json.JSONException: JSONObject["claims"] is not a JSONArray.

### ISSUE THREAD

**Issue by alismayilov** [Wikidata/Wikidata-Toolkit#121] opened 2015-02-22 20:32 UTC
We use wikidata toolkit for wikidata extraction. It works fine for most of the pages. However, for some pages, I got "org.json.JSONException: JSONObject["claims"] is not a JSONArray." error. I don't get this error for very old dumps (August - 2014). I got it when I use newer dumps.

**Comment by mkroetzsch** [comment] 2015-02-22 20:58
Which dump file are you working with (date and type). If you are using JSON dumps, the message should also say something about "recovery mode" after the first occurrence, and it should specify a line number there as well. The current WDTK code has special facilities to recover from malformed JSON in the dumps, which still seems to occur from time to time.

If some error of this type is suddenly much more frequent in the dumps, we need to check if the JSON is really broken, and report a bug to the Wikidata team so that they can have a look. There is also a small chance that the JSON is valid and WDTK is not prepared to accept it for some reason that lies in our code, but the message you get seems to indicate a very fundamental structural error in the JSON.

**Comment by alismayilov** [comment] 2015-02-22 21:14
We use XML dumps. I was testing with following dump: http://dumps.wikimedia.org/other/incr/wikidatawiki/20150207/
For exampling, it fails to extract "Q7560" item.

**Comment by mkroetzsch** [comment] 2015-02-22 21:20
Ok, we would need to check what the JSON for this item is inside the file, especially what the value of "claims" is. My guess is that is is {} (the empty map); this is the usual error we are seeing and there should already be a bug report against Wikibase for this (the correct value would be [], the empty array, in this case).

Btw. is there a reason you are using the XML dumps? The JSON dumps should be faster to parse. The only advantage of the XML dumps is that you get non-data Wiki pages, revision data (user, date), and possibly old revisions (if using). If you only need the data content, JSON is preferred.

**Comment by alismayilov** [comment] 2015-02-22 22:01
Because DBpedia already has XML parser, I used it. We might also implement JSON parser. But for now, I use XML parser. 
I checked value of "claims" for "Q7560" with online json validator, it is valid json. Please find claims for Q7560 in following link: https://www.dropbox.com/s/tw4l78wcqxa53ut/claims_for_Q7560?dl=0

**Comment by fer-rum** [comment] 2015-02-23 10:41
Judging from ther error message, I suspect you are not using the Jackson-based parser, but the older org.json-code.
May I ask, how you start the Json parsing process and which version of WDTK you are using?

**Comment by mkroetzsch** [comment] 2015-02-23 14:17
> Because DBpedia already has XML parser, I used it. We might also implement JSON parser. But for now, I use XML parser. 

I am confused here. WDTK has an XML parser and a JSON parser. How can you make use of the DBpedia parser in combination with WDTK?

**Comment by fer-rum** [comment] 2015-02-23 16:16
That enhances my suspicion since it is the legacy parser that is coupled to the XML parsing (as far as I am aware).

(@mkroetsch)Let me try to get things a bit clearer:

@alismayilov does have XML-files. He *could* parse them with DBpedias XML-parser to obtain the contained JSON. But *actually* he decided to use the XML-parser delivered with the WDTK, which also handles the JSON. And this is where the error occurs. (Please correct me if I understood this wrong.)

The reason behind this is that only the legacy version of the wikidata dumps was XML-wrapped JSON. It used a different JSON-format than the newer (pure-JSON) dumps do. So my thought is: If you have a facility already to get the JSON out of XML, use it and parse the JSON using the current Jackson-based parser. You may also refer to (the seemingly related issue) #89 for a (very) minimal example.

**Comment by alismayilov** [comment] 2015-02-23 23:49
@mkroetzsch I use DBpedias XML parser to obtain JSON. And then I parse this JSON using the WDTK. 
@fer-rum I use 0.3.0 version. I try to parse JSON using Jackson-based parser. If there is an Throwable exception, I use old JSON parser. Here is the code I use: 
![code](https://cloud.githubusercontent.com/assets/1295876/6340344/b9ab236c-bbbe-11e4-9a1b-2eebafd338d7.png)
You are right, I got this error because of org.json - code. Without org.json I got following error: 
WARNING: error processing page 'title=Q4748;ns=0/Main/;language:wiki=wikidata,locale=en': com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.Linke ...97 chars omitted... 7] (through reference chain: org.wikidata.wdtk.datamodel.json.jackson.JacksonItemDocument["claims"])

**Comment by fer-rum** [comment] 2015-02-24 10:57
Okay, I have never seen this language/dialect before.
The basic problem is not that the JSON is syntactically invalid; But that it seems to describe the claims as an object, not an array which is semantic garbage.
(@mkroetzsch Are you aware of any recent changes or can you confirm the last half sentence?)
As far as I know, there might be still a bunch of items, that might be broken in one way or the other due to historical reasons.
A possible quickfix might be to change the *{…}* pair following *"claims":* to *[…]* how it is supposed to be and hopefully it will parse just fine.
@mkroetzsch What do you think about automating the recognition of such problems and fixing them on the fly to imporove robustness?

**Comment by mkroetzsch** [comment] 2015-02-24 16:35
So do we agree now that this is simply malformed JSON content, and that WDTK correctly recognizes this error and rejects the broken data as it should? I don't think it would make sense for us to work around such errors if they are simply known Wikibase bugs that are expected to be fixed sometime soon (fingers crossed). If this is the conclusion, I suggest we simply close this issue (and ideally also link to the relevant Wikibase bug that can be watched).

> @mkroetzsch What do you think about automating the recognition of such problems and fixing them on the fly to imporove robustness?

Our regular JSON file processor already is robust to arbitrary JSON errors in the sense that it will only ignore the broken item and continue with the remaining data without crashing. Adding special handling to fix individual glitches seems not the best use of our resources unless the errors become so frequent again that it really becomes an issue. Last time I checked, such problems affected less than 10 out of 16 million items, which seems acceptable, esp. considering the fact that affected items usually had zero claims (so are irrelevant for all processing steps that look at the claims).

**Comment by fer-rum** [comment] 2015-02-25 11:19
Agreed. This would be my resolution as well.
@alismayilov If you do really depend on every item beeing parsed somehow, I fear it comes down to forging custom solutions.

**Comment by jimkont** [comment] 2015-02-25 11:30
Thanks for looking into this and no I don't think it matters that much to
go for a custom solution. It is a small percentage but I think is higher
than the estimations of @mkroetzsch
@alismayilov can you count/collect the failed pages as a reference here?

**Comment by alismayilov** [comment] 2015-02-26 07:13
Fail rate is much higher than I thought. It starts with low rate (that is why I thought few pages fails). For example: 4 pages fail out of 22000. 
It is still running, I am waiting for to see how many pages will fail for whole dump. It seems it will be very high. For now fail rate is  ~24%. 
wikidata: extracted 12656000 pages in 375:10.630s (per page: 1.7786528128950696 ms; failed pages: 3070817).

**Comment by mkroetzsch** [comment] 2015-02-26 08:18
@alismayilov Ok, we will investigate. What dump file are you currently using?

**Comment by alismayilov** [comment] 2015-02-26 08:31
@mkroetzsch, thank you. This one http://dumps.wikimedia.org/wikidatawiki/20150207/wikidatawiki-20150207-pages-articles.xml.bz2

**Comment by mkroetzsch** [comment] 2015-02-26 13:19
After some tests, I can confirm that large parts of the XML dump are indeed broken. In contrast, the JSON dump is almost free of errors (in a quick test, I got 17260070 items and 1396 properties that were parsed without problems). Thus, at the moment, it is only possible to use the JSON dumps. I will send another email about this (recurring) issue to the wikidata mailing list; I am not sure if they are aware of this (it is strange already that the JSON is actually different in the two dump formats).

I am closing this bug since the problem is in the buggy dump files, which we cannot fix. I have also checked and found that the problem is not limited to one kind of map that is wrongly exported in the dumps: all maps (aliases, descriptions, claims, ...) seem to be exported wrongly if empty. This makes it very hard to work around the issue in our code (basically every map in every Java object we use would need special checks or custom JSON mapping code).

**Closed by mkroetzsch** 2015-02-26 13:19 UTC

**Comment by jimkont** [comment] 2015-02-26 13:36
Thanks again for looking into this @mkroetzsch & @fer-rum 
We already check the wikidata ml but if you submit this directly to phabricator please post back the issue link.

**Comment by mkroetzsch** [comment] 2015-02-27 20:05
The issue is tracked at https://phabricator.wikimedia.org/T91117 now.

**Comment by jimkont** [comment] 2015-03-10 11:22
Hi, I am adding another error we got and not sure if it is about the same issue
```
WARNING: error processing page 'title=Q565679;ns=0/Main/;language:wiki=wikidata,locale=en': com.fasterxml.jackson.databind.JsonMappingException: Unexpected token (END_OBJECT), expected FIELD_N ...118 chars omitted... rmedStatementDocument)
 at [Source: {"entity":"Q565679","redirect":"Q4769395"}; line: 1, column: 42]
```

**Comment by jimkont** [comment] 2015-03-10 14:21
@mkroetzsch & @fer-rum another question on this.
The error rate is quite high at the moment ~20%, is there a quick hack / util function from WDTK we could use to preprocess the json and remove empty values or convert arrays to objects?
From my understanding these are the main causes of these issues, right?
We are not so familiar with the official json structure and any help in this will be highly appreciated.

To make it complete, we get two types of errors and the first one (descriptions) is more common than claims
```
WARNING: error processing page 'title=Q2384172;ns=0/Main/;language:wiki=wikidata,locale=en': com.fasterxml.jackson.databind.JsonMappingException: 
Can not deserialize instance of java.util.Linke ...570 chars omitted... rough reference chain: org.wikidata.wdtk.datamodel.json.jackson.JacksonItemDocument["descriptions"])
WARNING: error processing page 'title=Q2386578;ns=0/Main/;language:wiki=wikidata,locale=en': com.fasterxml.jackson.databind.JsonMappingException: 
Can not deserialize instance of java.util.Linke ...367 chars omitted... 8] (through reference chain: org.wikidata.wdtk.datamodel.json.jackson.JacksonItemDocument["claims"])
```
