### ISSUE TITLE
DataModel for JacksonInnerEntityId is broken

### ISSUE THREAD

**Issue by jinang** [Wikidata/Wikidata-Toolkit#237] opened 2016-08-04 03:14 UTC
JSON data returned from wbgetentities api has additional 'id' string property added. Breaking serialization of JacksonInnerEntityId.

Data extract form https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q42
` "datavalue": { "value": { "entity-type": "item", "numeric-id": 5, "id": "Q5" }`

**Comment by mkroetzsch** [comment] 2016-08-04 05:23
Is it known when this change was made? It seems the dump processing has worked until recently.

**Comment by jinang** [comment] 2016-08-04 05:40
I'm not sure when the change has been made but it must be fairly recent.
I only found out today when my application failed to get any item documents using wbgetentities, due to serialization errors.

**Comment by mkroetzsch** [comment] 2016-08-04 11:16
The issue is fixed in master now. A new release is still pending.

**Closed by mkroetzsch** 2016-08-04 11:16 UTC
